services:
  db:
    image: postgres:15
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: teebay-api
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: teebay
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql@15/data

  db-client:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./teebay-api
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # DATABASE_URL: postgres://teebay-api:123456789@172.17.0.1:5432/teebay
      DATABASE_URL: postgres://teebay-api:123456789@host.docker.internal:5432/teebay
    depends_on:
      - db

  frontend:
    build:
      context: ./teebay-frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:
